### ISSUE TITLE
OpenWRT 18.06.0 Build

### ISSUE THREAD

**Issue by thecheatah** [firehol/packages#7]
Create a build for the latest release of [OpenWRT 18.06.0](https://openwrt.org/releases/18.06/notes-18.06.0).

**Comment by philwhineray** [comment]
Done! Note: I haven't got a system to test it on personally.

**Comment by philwhineray** [comment]
Tried deploying the package and hit problems. A new version is now up. FireQOS has problems with its status command which are now fixed in the firehol repo by this commit:

https://github.com/firehol/firehol/commit/193b3ed5224cb57d664c2c9b7dfe26bf854f63ca

I don't have time to make a new release right now - it is trivial to edit `/sbin/fireqos` in situ to apply the change if you need this to work.
