### ISSUE TITLE
Error: Nothing provides iptables-ipv6 needed by firehol

### ISSUE THREAD

**Issue by uok** [firehol/packages#9]
Just by looking at the documentation I'm very excited to use FireHOL
Thanks for this great piece of software!

Unfortunately I have trouble installing FireHOL on CentOS 8
`yum --nogpgcheck localinstall firehol-x.y.z-1.el7.centos.noarch.rpm`
gives error
`Nothing provides iptables-ipv6 needed by firehol`

I tried firehol-3.1.5-1.el7.centos.noarch.rpm and firehol-3.1.6-1.el7.noarch.rpm without success

Can you please help? Thanks!

**Comment by philwhineray** [comment]
Looks like the dependent packages have changed from 7 to 8.

I would try [downloading](https://firehol.org/installing/#download) and installing from [source](https://firehol.org/installing/#install) - there isn't really anything to compile, so it is not onerous.

If you really want to use an rpm, then you could try running yum with `--no-check` which is not ideal, and you may be left with other problems.

Otherwise someone (could be you!) needs to take a look at the [packages](https://github.com/firehol/packages) repo and extend the scripts in there to add builds for the extra CentOS/EL version.

**Comment by KyleMaas** [comment]
This one should be fixed with #16 being merged.

**Comment by philwhineray** [comment]
Updated packages are now published and should solve it for you, but feel free to re-open if not.
